export const getPlays = () => {
  const plays = [
    { title: "All's Well That Ends Well", year: 1602 },
    { title: "Antony and Cleopatra", year: 1606 },
    { title: "As You Like It", year: 1599 },
    { title: "Comedy of Errors", year: 1589 },
    { title: "Coriolanus", year: 1607 },
    { title: "Cymbeline", year: 1609 },
    { title: "Hamlet", year: 1600 },
    { title: "Henry IV, Part I", year: 1597 },
    { title: "Henry V ", year: 1598 },
    { title: "Henry IV, Part II ", year: 1597 },
    { title: "Henry VI, Part I ", year: 1591 },
    { title: "Henry VI, Part II ", year: 1590 },
    { title: "Henry VI, Part III ", year: 1590 },
    { title: "Henry VIII ", year: 1612 },
    { title: "Julius Caesar ", year: 1599 },
    { title: "King John ", year: 1596 },
    { title: "King Lear ", year: 1605 },
    { title: "Love's Labour's Lost ", year: 1594 },
    { title: "Macbeth ", year: 1605 },
    { title: "Measure for Measure ", year: 1604 },
    { title: "Merchant of Venice ", year: 1596 },
    { title: "Merry Wives of Windsor ", year: 1600 },
    { title: "Midsummer Night's Dream ", year: 1595 },
    { title: "Much Ado about Nothing ", year: 1598 },
    { title: "Othello ", year: 1604 },
    { title: "Pericles ", year: 1608 },
    { title: "Richard II ", year: 1595 },
    { title: "Richard III ", year: 1592 },
    { title: "Romeo and Juliet ", year: 1594 },
    { title: "Taming of the Shrew ", year: 1593 },
    { title: "Tempest ", year: 1611 },
    { title: "Timon of Athens ", year: 1607 },
    { title: "Titus Andronicus ", year: 1593 },
    { title: "Troilus and Cressida ", year: 1601 },
    { title: "Twelfth Night ", year: 1599 },
    { title: "Two Gentlemen of Verona ", year: 1594 },
    { title: "Winter's Tale ", year: 1610 },
  ];

  return plays;
};